name: generate animation

on:
  # run every day at midnight UTC
  schedule:
    - cron: "0 0 * * *"
  # allow manual trigger
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate GitHub contribution snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: TarunReddy77
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push SVGs to the `output` branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
