name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: TarunReddy77
          outputs: |
            ./output/github-contribution-grid-snake.svg
            ./output/github-contribution-grid-snake-dark.svg
          theme: github-light
          theme_dark: github-dark

      - name: Push the generated files
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "chore: generate snake contribution grid"
          add: "output/*.svg"
          force: true       # ✅ ADD THIS LINE
